### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ameistad** [bluebeel/now-nuxt#3]
I'm trying to get my nuxt project working with version 2 and this build, but I'm getting build errors.

## now.json
```json
{
  "version": 2,
  "name": "nuxt",
  "alias": "nuxt.example.com",
  "env": {
    "NODE_ENV": "production",
  },
  "builds": [
    { "src": "nuxt.config.js", "use": "@bluebeel/nuxt" }
  ]
}

```

## Error log
```
12/30 11:56 PM (5m)
error /tmp/69374d61/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /tmp/69374d61/node_modules/cypress
Output:
Installing Cypress (version: 3.1.4)

?25l[22:56:11]  Downloading Cypress     [started]
[22:56:12]  Downloading Cypress      0% 0s [title changed]
[22:56:12]  Downloading Cypress      4% 2s [title changed]
[22:56:12]  Downloading Cypress      10% 2s [title changed]
[22:56:12]  Downloading Cypress      15% 2s [title changed]
[22:56:12]  Downloading Cypress      21% 2s [title changed]
[22:56:12]  Downloading Cypress      27% 1s [title changed]
[22:56:12]  Downloading Cypress      32% 1s [title changed]
[22:56:12]  Downloading Cypress      38% 1s [title changed]
[22:56:12]  Downloading Cypress      42% 1s [title changed]
[22:56:13]  Downloading Cypress      47% 1s [title changed]
[22:56:14]  Downloading Cypress      53% 2s [title changed]
[22:56:14]  Downloading Cypress      57% 1s [title changed]
[22:56:14]  Downloading Cypress      62% 1s [title changed]
[22:56:14]  Downloading Cypress      69% 1s [title changed]
[22:56:14]  Downloading Cypress      74% 1s [title changed]
[22:56:14]  Downloading Cypress      81% 1s [title changed]
[22:56:14]  Downloading Cypress      87% 0s [title changed]
[22:56:14]  Downloading Cypress      93% 0s [title changed]
[22:56:14]  Downloading Cypress      100% 0s [title changed]
[22:56:14]  Downloaded Cypress      [title changed]
[22:56:14]  Downloaded Cypress      [completed]
[22:56:14]  Unzipping Cypress       [started]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]  Unzipping Cypress        0% 0s [title changed]
[22:56:14]
12/30 11:56 PM (5m)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
12/30 11:56 PM (5m)
patching https://api-bru1.zeit.co/v2/now/deployments/dpl_F9wfTrTtPzNKPrBPJNbxPiJ1J6op/builds/bld_8act7psak with {"readyState":"ERROR","errorCode":"BUILD_FAILED"}
12/30 11:56 PM (5m)
{ Error: Exited with 1
    at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:11:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) reported: true }
```

Does it has something to do with devDependencies (Cypress) being installed?

**Comment by bluebeel** [comment]
Hi,

Cypress is a big lib and I think your build exceeds the limit imposed by zeit for each build that I remember is 500mb.
Have you tried to build without this dependency?

**Comment by dohomi** [comment]
@bluebeel is is maybe an option to run `npm run build` on the local machine and then just upload the already compiled `.nuxt` folder to now and don't build it online on zeit servers?

**Comment by bluebeel** [comment]
@dohomi The builder doesn't do it actually but it is an option quite possible.
Currently I am busy looking at how we could reduce the build time on now which isn't caused in itself by the build of nuxt but more the creation of the lambdas (#2).
