### ISSUE TITLE
Error in build which then fails. 

### ISSUE THREAD

**Issue by michaelpumo** [bluebeel/now-nuxt#7]
I'm trying to get Nuxt running on V2.

**now.json**

```
{
  "name": "point-campus",
  "version": 2,
  "alias": [
    "www.pointcampus.ie"
  ],
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@bluebeel/nuxt"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "status": 301,
      "headers": {
        "Location": "https://pointcampus.ie/$1"
      }
    }
  ]
}
```

If I then run `now`, I get the following message:

```
> Deploying ~/Documents/websites/point-campus under pointcampus
> Using project point-campus
> Synced 3 files (5.49KB) [1s]
> https://point-campus-f7tudmgty.now.sh [v2] [in clipboard] [5s]
╶ nuxt.config.js        Error               [59s]
> Error! 1 build failure occured.
```

If I then look at the logs...it spits out a load of info but it's at this point that the log states there's an error:

```
2019-01-25T15:49:48.765Z  error prismic-nuxt@0.3.0: The engine "node" is incompatible with this module. Expected version ">= 9.0.0". Got "8.10.0"
2019-01-25T15:49:48.781Z  error Found incompatible module
2019-01-25T15:49:48.781Z  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2019-01-25T15:49:48.805Z  Error: Exited with 1
                              at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:14:16)
                              at emitTwo (events.js:126:13)
                              at ChildProcess.emit (events.js:214:7)
                              at maybeClose (internal/child_process.js:925:16)
                              at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-01-25T15:49:48.805Z  patching https://api-bru1.zeit.co/v2/now/deployments/dpl_7HHKGc37rcW7b7SFEyPprLAHkqxP/builds/bld_mhh1i0rq0 with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
```

If I check in the `prismic-nuxt@0.3.0` node module, I see it states:

```
"engines": {
  "node": ">= 9.0.0",
  "npm": ">= 6.0.0"
}
```

So I'm not sure why that's breaking if it states the expected version is ">= 9.0.0"?

I know in the docs it states to update the Nuxt config file to utilise:

```
module.exports = () => {
  return {}
}
```

But if I do that, I get errors running the dev build (`npm run dev`).

My current config setup is in this format (just an object):

`module.exports = {}`

Could that be the issue at hand?

Thanks

**Comment by bluebeel** [comment]
The problem doesn't come from my builder.
You are using a specific libray that expect a node version >= 9.0.0
The available runtime on `zeit now` are **8.10** and **6.10**

**Comment by michaelpumo** [comment]
Ahh that would be it then, of course! Apologies. I will investigate to see if it's possible on Zeit to adjust the Node version.

If that's not possible, I'm out of ideas on how to work around this since it's a 3rd party node module. I'll also query the developer of that module.

Thank you.

**Comment by bluebeel** [comment]
We can't for the moment adjust the node runtime. They will probably add the node9 or node10 runtime sooner or later.
