### ISSUE TITLE
Not working with a fresh template created with create-nuxt-app

### ISSUE THREAD

**Issue by nles** [bluebeel/now-nuxt#8]
I did the following
```
yarn create nuxt-app nuxt-test
cd nuxt-text
# create now.json with same content as in bluebeel/now-nuxt/README.md
# made changes to nuxt.config.js according to bluebeel/now-nuxt/README.md
now
```

It goes through the build just fine (although it takes about 15 minutes, which I guess is expected). After navigating to the route, I get an error (ERR_INVALID_RESPONSE)

The logs say
```
02/05 02:35 PM (7m)
Unable to import module 'now__launcher': Error
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/nuxt.config.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
02/05 02:35 PM (7m)
REPORT RequestId: 305447d6-ef7d-4c21-bc9f-11dd18a0344c	Duration: 0.48 ms	Billed Duration: 100 ms 	Memory Size: 3008 MB	Max Memory Used: 92 MB
```

create-nuxt-app config

```
? Project name nuxt-test                                                                                                                                                                       
? Project description My glorious Nuxt.js project                                                                                                                                              
? Use a custom server framework none                                                                                                                                                           
? Choose features to install Progressive Web App (PWA) Support, Linter / Formatter, Prettier, Axios                                                                                            
? Use a custom UI framework vuetify                                                                                                                                                            
? Use a custom test framework jest                                                                                                                                                             
? Choose rendering mode Universal                                                                                                                                                              
? Author name Me
```

**Comment by ergofriend** [comment]
same eroor, me too :(

**Comment by ergofriend** [comment]
sry, I forgot to edit nuxt.config.js is.
But, then build passed, I got 'Nuxt.js Internal Server Error'.
https://tento.now.sh/
```
{
  "status": 500,
  "message": "Cannot find module 'pages/index.js' from '/var/task'",
  "name": "NuxtServerError"
}
```

**Comment by bluebeel** [comment]
can you show the output src and the nuxt.config.js file pls?

**Comment by ergofriend** [comment]
if it works, mine, this is the repo.
https://github.com/tento-app/tento-nuxt
